# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/log.proto\",\n\nLogMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t21\n\nLogService\x12#\n\x07SendLog\x12\x0b.LogMessage\x1a\x0b.LogMessageb\x06proto3')



_LOGMESSAGE = DESCRIPTOR.message_types_by_name['LogMessage']
LogMessage = _reflection.GeneratedProtocolMessageType('LogMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOGMESSAGE,
  '__module__' : 'proto.log_pb2'
  # @@protoc_insertion_point(class_scope:LogMessage)
  })
_sym_db.RegisterMessage(LogMessage)

_LOGSERVICE = DESCRIPTOR.services_by_name['LogService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGMESSAGE._serialized_start=19
  _LOGMESSAGE._serialized_end=63
  _LOGSERVICE._serialized_start=65
  _LOGSERVICE._serialized_end=114
# @@protoc_insertion_point(module_scope)
