apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-grpc-api
  name: udaconnect-grpc-api
spec:
  ports:
  - name: "50052"
    port: 50052
    targetPort: 50051
    nodePort: 30151
  selector:
    service: udaconnect-grpc-api
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-grpc-api-internal
  name: udaconnect-grpc-api-internal
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    service: udaconnect-grpc-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-grpc-api
  name: udaconnect-grpc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-grpc-api
  template:
    metadata:
      labels:
        service: udaconnect-grpc-api
    spec:
      containers:
      - image: beebeewijaya/udaconnect-logger-grpc:latest
        name: udaconnect-grpc-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_HOST
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_PORT
      restartPolicy: Always
