# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/location.proto\"m\n\x10LocationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tperson_id\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t\"I\n\x0fLocationRequest\x12\x11\n\tperson_id\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\"#\n\x15LocationDetailRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"<\n\x14LocationListResponse\x12$\n\tlocations\x18\x01 \x03(\x0b\x32\x11.LocationResponse2\xb3\x01\n\x0fLocationService\x12\x38\n\x0bGetLocation\x12\x16.LocationDetailRequest\x1a\x11.LocationResponse\x12\x34\n\x0e\x43reateLocation\x12\x10.LocationRequest\x1a\x10.LocationRequest\x12\x30\n\x0fGetLocationList\x12\x06.Empty\x1a\x15.LocationListResponseb\x06proto3')



_LOCATIONRESPONSE = DESCRIPTOR.message_types_by_name['LocationResponse']
_LOCATIONREQUEST = DESCRIPTOR.message_types_by_name['LocationRequest']
_LOCATIONDETAILREQUEST = DESCRIPTOR.message_types_by_name['LocationDetailRequest']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_LOCATIONLISTRESPONSE = DESCRIPTOR.message_types_by_name['LocationListResponse']
LocationResponse = _reflection.GeneratedProtocolMessageType('LocationResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONRESPONSE,
  '__module__' : 'proto.location_pb2'
  # @@protoc_insertion_point(class_scope:LocationResponse)
  })
_sym_db.RegisterMessage(LocationResponse)

LocationRequest = _reflection.GeneratedProtocolMessageType('LocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONREQUEST,
  '__module__' : 'proto.location_pb2'
  # @@protoc_insertion_point(class_scope:LocationRequest)
  })
_sym_db.RegisterMessage(LocationRequest)

LocationDetailRequest = _reflection.GeneratedProtocolMessageType('LocationDetailRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONDETAILREQUEST,
  '__module__' : 'proto.location_pb2'
  # @@protoc_insertion_point(class_scope:LocationDetailRequest)
  })
_sym_db.RegisterMessage(LocationDetailRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.location_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

LocationListResponse = _reflection.GeneratedProtocolMessageType('LocationListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONLISTRESPONSE,
  '__module__' : 'proto.location_pb2'
  # @@protoc_insertion_point(class_scope:LocationListResponse)
  })
_sym_db.RegisterMessage(LocationListResponse)

_LOCATIONSERVICE = DESCRIPTOR.services_by_name['LocationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONRESPONSE._serialized_start=24
  _LOCATIONRESPONSE._serialized_end=133
  _LOCATIONREQUEST._serialized_start=135
  _LOCATIONREQUEST._serialized_end=208
  _LOCATIONDETAILREQUEST._serialized_start=210
  _LOCATIONDETAILREQUEST._serialized_end=245
  _EMPTY._serialized_start=247
  _EMPTY._serialized_end=254
  _LOCATIONLISTRESPONSE._serialized_start=256
  _LOCATIONLISTRESPONSE._serialized_end=316
  _LOCATIONSERVICE._serialized_start=319
  _LOCATIONSERVICE._serialized_end=498
# @@protoc_insertion_point(module_scope)
